### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by rioniac** [CamHenlin/imessageclient#12]
Trying to install, and getting the following issues at the end:

    npm ERR! Darwin 14.1.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.0
    npm ERR! code ELIFECYCLE

    npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sqlite3@3.0.4 install script 'node-pre-gyp install --fallback-to-build'.
    npm ERR! This is most likely a problem with the sqlite3 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --fallback-to-build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls sqlite3
    npm ERR! There is likely additional logging output above.

**Comment by CamHenlin** [comment]
I think this is a dupe of #7, which turned out to be a problem with the user's nodejs installation

**Comment by rioniac** [comment]
Yes, uninstalling nodejs and nom via homebrew and then installing nodejs v0.10.35 pkg from nodejs.org solved the problem.  Thanks!
