### ISSUE TITLE
Crash when sending message

### ISSUE THREAD

**Issue by Haroenv** [CamHenlin/imessageclient#18]
`Messages.app` is open

permissions are given ![screenshot](https://i.imgur.com/NAZfJhU.png) to `Terminal.app`

error message:
```
we have a file to monitor!
Error: /Users/haroenviaene/git/imessageclient/sendmessage_single.AppleScript:170:262: execution error: System Events got an error: Can’t get window 1 of process "Messages". Invalid index. (-1719)

    at ChildProcess.<anonymous> (/Users/haroenviaene/git/imessageclient/applescript/lib/applescript.js:54:13)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
```

**Comment by CamHenlin** [comment]
Hi Haroenv, sorry for the inconvenience. Could you revert back to commit `5827bfb875be5dba73cd73aaf3b3eba38bb5a532`

by doing:
```
git checkout 5827bfb875be5dba73cd73aaf3b3eba38bb5a532 . 
```
And retrying and let me know if that fixes things for you?

**Comment by Haroenv** [comment]
I checked out, but when doing that, `npm install` gives an error: 

```
npm WARN package.json imessageclient@1.0.0 No repository field.
```

and when sending a message (I didn’t reinstall, but it seemed to be different), it flashes the destination and then the message quickly, but it doesn’t send anything (not on the CLI, not on the app).

**Comment by CamHenlin** [comment]
Yeah the checkout shouldn't have required it another npm install. It was changing back the AppleScript files used to send the messages to an earlier revision. It seems to me that if it's flashing the app and everything on the screen, it is attempting to send. Is Messages.app signed in to an iMessage account? Is Messages.app popping up with any error dialogs?

**Comment by Haroenv** [comment]
nope, Messages just stays idle and open, nothing happens

**Comment by CamHenlin** [comment]
Can you send the iMessages using only the AppleScript files in the imessageclient directory? You can give it a shot by using this:

```
osascript sendmessage_single.AppleScript "someimessage@emailaddresss" "test message" false false
```
Note that the first false might have to be true if you have "Full Keyboard Access" turned on in your System Settings

**Comment by Haroenv** [comment]
the output of that script is: 

````
whoI@sended-it.to <mailto:whoI@sended-it.to>
	message
```

when using `false false`, and 

````
whoI@sended-it.to <mailto:whoI@sended-it.to>
		message
```

(so a different amount of tabs)

I’m on 10.10.3 beta though

> On 23 Mar 2015, at 23:23, Cameron Henlin <notifications@github.com> wrote:
> 
> Can you send the iMessages using only the AppleScript files in the imessageclient directory? You can give it a shot by using this:
> 
> osascript sendmessage_single.AppleScript "someimessage@emailaddresss" "test message" false false
> Note that the first false might have to be true if you have "Full Keyboard Access" turned on in your System Settings
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/CamHenlin/imessageclient/issues/18#issuecomment-85230192>.
>

**Comment by CamHenlin** [comment]
Okay, that script is actually silent so that means that the AppleScript is not able to grab the Messages.app window to type in the message. Are you clicking/cmd+tabbing away from the Messages window when it pops up? Or are you using a different locality setting on your Mac, and maybe the Messages window is named something else? I am looking for a process named "Messages" right now, maybe that isn't right for you?

**Comment by Haroenv** [comment]
There is a Messages process, I looked in top, and it's called the same.

As far as I see, the window is called Messages too

It doesn't switch to messages though, it just displays without leaving terminal

**Comment by Haroenv** [comment]
Wait a minute? It works when Terminal isn't full screen!

And so does your app

**Comment by CamHenlin** [comment]
Wow! So full screen breaks the App? Veeeery interesting

**Comment by Haroenv** [comment]
Could be an issue at my part though, I've had other issues concerning full screen I've still got to look at

**Comment by CamHenlin** [comment]
Nope, I just confirmed this on my end. Surprising that it hasn't come up sooner to be honest.

**Comment by CamHenlin** [comment]
Thanks for reporting this and helping figure out the problem. I'm hoping there's something I can do to fix it shortly

**Comment by Haroenv** [comment]
No problem, thanks for helping to figure it out. 

The master now works too by the way

**Comment by CamHenlin** [comment]
Okay, I just pushed an update that basically activates the Messages app first, which will slide you out of the fullscreen terminal app to send the Message. Definitely sort of clunky but at least it doesn't fail

**Comment by Haroenv** [comment]
Now it crashes again in full screen 

```
we have a file to monitor!
Error: /Users/haroenviaene/git/imessageclient/sendmessage_single.AppleScript:196:288: execution error: System Events got an error: Can’t get window 1 of process "Messages". Invalid index. (-1719)

    at ChildProcess.<anonymous> (/Users/haroenviaene/git/imessageclient/applescript/lib/applescript.js:54:13)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
```

**Comment by CamHenlin** [comment]
Okay, I added another check, it should work for you now. Unfortunately the way it's working right now, it won't make it back to your full screen app so you'll need a cmd+tab to make it back there. I'm going to work on fixing that this evening

**Comment by CamHenlin** [comment]
Hi Haroenv, I just pushed another update to imessageclient which aims to fix the reliability issues with full screen. It seems to work about as well as is possible with AppleScript, so until https://github.com/CamHenlin/nodeprivatemessageskit is further along, it will have to do. Can you try out the latest version and let me know what you think so I can mark this issue as closed?

**Comment by Haroenv** [comment]
yep :+1: works perfectly!

**Comment by Haroenv** [comment]
That works smoothly 

Haroen

**Comment by CamHenlin** [comment]
Very good, thank you!
