### ISSUE TITLE
Gracefully handle lack of assistive access

### ISSUE THREAD

**Issue by twodayslate** [CamHenlin/imessageclient#19]
Error: /Users/zac/imessageclient/sendmessage_single.AppleScript:167:179: execution error: System Events got an error: osascript is not allowed assistive access. (-1719)
    at ChildProcess.<anonymous> (/Users/zac/imessageclient/applescript/lib/applescript.js:54:13)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12) 

Instead of crashing when assistive access is not allowed, either fix the problem or prompt the user to allow access with instructions.

**Comment by CamHenlin** [comment]
Hi, twodayslate, thanks for reporting your issue. I'm taking a look at things right now and hoping to have something more graceful for you shortly. :)

**Comment by CamHenlin** [comment]
Hi twodayslate, I just pushed commit 7f0549c, which resolves this issue. Could you check it out and let me know if it meets your expectations?

**Comment by twodayslate** [comment]
Got a GUI popup. Great work. 

In addition to [line 8](https://github.com/CamHenlin/imessageclient/commit/ceebaed06ce9de802f0efec6fe4559870450bad2#diff-b42f2e5f8193efc0a9629efb5c2f8b74R8) you should add a warning in the terminal application.

**Comment by CamHenlin** [comment]
Went ahead and added it to the main chatbox, thanks for the suggestion :+1:
