### ISSUE TITLE
Error: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by camslupeiks** [CamHenlin/imessageclient#24]
When I try to run the app using node app, I get the following error message:

Error: SQLITE_CANTOPEN: unable to open database file

Could someone give me instructions on how to fix this? I am trying to run the app on macOS Mojave v10.14.4. I have also given system permissions to terminal.app.

**Comment by hmenzagh** [comment]
Same issue here

**Comment by incandescentman** [comment]
same here

**Comment by canalnoises** [comment]
Same for me. Just tried installing on macOS 10.14.6.

**Comment by mr-sk** [comment]
Same here - anyone have a solution?

I think it has to do w/the fact there is no chat.db at the location in the app.js file.

**Comment by 1outres** [comment]
same here

**Comment by aksperiod** [comment]
Same here

**Comment by wrobbins** [comment]
Go to system preferences --> Security & Privacy --> full disk access (left hand side) --> check terminal/iTerm or whatever terminal you use

**Comment by canalnoises** [comment]
@wrobbins Hey, that worked! Thanks!
