### ISSUE TITLE
Subsequent message composition yields invisible text entry

### ISSUE THREAD

**Issue by justinmayer** [CamHenlin/imessageclient#3]
Once I send a message, typing a subsequent message in the same conversation results in invisible text (or at least that's what it looks like — the cursor advances on each keystroke but without any characters shown).

**Comment by CamHenlin** [comment]
Thanks, I'll look into this in a few hours. I think I might have to modify blessed, the display library I'm using: https://github.com/chjj/blessed

**Comment by CamHenlin** [comment]
Fixed it!
