### ISSUE TITLE
Requires extra tab on systems with "Full keyboard access" set to "All controls"

### ISSUE THREAD

**Issue by jtokoph** [CamHenlin/imessageclient#6]
#### See bottom section of this screen for the setting I have enabled:
![screen shot 2015-02-07 at 6 18 25 pm](https://cloud.githubusercontent.com/assets/346225/6094898/db7929ba-aef5-11e4-998f-2c553f9bdadc.png)

#### Add recipient button becomes next tab target after recipient entry field:
![screen shot 2015-02-07 at 6 18 42 pm](https://cloud.githubusercontent.com/assets/346225/6094899/de2e154e-aef5-11e4-9800-fa5f7edecf92.png)

#### Posible solution
Use a different apple script that tabs twice when all control access is enabled.

This setting can be queried via:

```bash
# When set to "All controlls"
$ defaults read NSGlobalDomain AppleKeyboardUIMode
3

# When set to text boxes and lists only
$ defaults read NSGlobalDomain AppleKeyboardUIMode
1
```

**Comment by CamHenlin** [comment]
Sweet! Thanks for the pointer, I will get on this

**Comment by CamHenlin** [comment]
Interesting, there's actually slightly more to it than that. On my system, before I enabled all controls, I got this:
Camerons-MacBook-Air:~ camh$ defaults read NSGlobalDomain AppleKeyboardUIMode
2015-02-07 22:20:04.992 defaults[1630:197434] 
The domain/default pair of (kCFPreferencesAnyApplication, AppleKeyboardUIMode) does not exist

Then after enabling:
Camerons-MacBook-Air:~ camh$ defaults read NSGlobalDomain AppleKeyboardUIMode
2

Then after disabling:
Camerons-MacBook-Air:~ camh$ defaults read NSGlobalDomain AppleKeyboardUIMode
0

**Comment by CamHenlin** [comment]
For now I am going to assume that one or less or error is set to text boxes and lists, and anything greater than 1 is set to all controls

**Comment by CamHenlin** [comment]
Fixed in latest version!

**Comment by ReeceMMI** [comment]
Hi, so I just wanted to make a minor update to this. As of MacOS Ventura, this option seems to now be a toggle shortcut that you access via CTRL+FN+F7. 

It is now also now located in Settings -> Keyboard -> Keyboard Shortcuts -> Keyboard -> "Change the way Tab moves focus"
