### ISSUE TITLE
Weird UI?

### ISSUE THREAD

**Issue by Doppp** [CamHenlin/imessageclient#9]
Not sure if it's just me or some settings I'm not doing right but my interface looks like this in iTerm2 instead of the one shown in the screenshot in the repo.

![screen shot 2015-02-08 at 4 24 20 pm](https://cloud.githubusercontent.com/assets/627410/6095916/2fab7df8-afaf-11e4-836d-d5569b165f69.png)

**Comment by CamHenlin** [comment]
Woah, yeah, it looks like blessed isn't playing nice with your settings. Not much I can do for that since I'm relying on a third party library for gui drawing
